import "./globals.css";
import { Roboto, Playfair } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400"]
})

const playfair = Playfair({
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <h1 className={roboto.className}>Hello AlmaBetter</h1>
      <h1 className={playfair.className}>Hello AlmaBetter</h1>
      <body>{children}</body>
    </html>
  );
}
